### PR TITLE
Add support for KMS and S3 references

### PR DESCRIPTION
**Pull request by RedbackThomson**
Issue #, if available: Fixes https://github.com/aws-controllers-k8s/community/issues/1649

Description of changes:
Adds reference fields for all references to S3 or KMS objects. There are additional references to Lambda, SNS and SQS fields - under the `Notification` configuration item - that can't be added yet until [an issue with reference field path detection](https://github.com/aws-controllers-k8s/community/issues/1610) is resolved.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
don't you just love it when stuff just works? :)

**Comment by A-Hilaly** [comment]
@RedbackThomson @jaypipes probably regression from https://github.com/aws-controllers-k8s/code-generator/pull/369. Time to revert? this is also impacting rds and ec2

**Comment by A-Hilaly** [comment]
Mmmm might be. The [error in the s3-unit-test](https://prow.ack.aws.dev/view/s3/ack-prow-logs/pr-logs/pull/aws-controllers-k8s_s3-controller/95/s3-unit-test/1620155395702001664) reminded of this P

**Comment by RedbackThomson** [comment]
/hold
It looks like there are some big issues with integrating resource references into these fields. It appears to be around lists of structs containing refs

**Pull request closed without merging**
