### PR TITLE
Fix grants being applied for default ACLs

### PR DESCRIPTION
**Pull request by RedbackThomson**
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1021

Description of changes:
A new bucket will have the `private` canned ACL by default. When adopting this bucket, the `ReadOne` in the controller will adopt it correctly, but will not be able to decide whether the ACL should be `private`, `bucket-owner-read` or `bucket-owner-full-control` (all have the same grants). The controller will set `Spec.ACL` to be a bar delimited list of these values, as well as list of grants that match these canned ACL policies. 

For the first reconciliation after adoption, the custom hook code was seeing a list of ACLs (rather than a single value) and did not know how to diff this against the described ACL possibilities. This was producing a faulty `PutBucketACLPayload` with values of both the canned ACL and the header grants - causing the error as described in the issue above.

This pull request ensures that the diff from the header grants will always be `nil` (by setting all header grants on `a` and `b` in the delta to `nil`) if a canned ACL is supplied. It also preemptively splits the `Spec.ACL` from the desired by the bar delimiter in case there have been multiple values joined in that field previously (most users won't see this functionality, but it needs to be there for adoption to work properly). Lastly, it never sets the grant header in the `PutBucketACLPayload` object if a canned ACL has already been specified. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — COMMENTED** [review]
@RedbackThomson code changes look great to me. Any chance of adding an e2e test for this?

**Comment by RedbackThomson** [comment]
> @RedbackThomson code changes look great to me. Any chance of adding an e2e test for this?

Good idea. This ACL stuff is a bit of a rat's nest of conditionals (blame the API, not me, please). I'll add some tests

**Review by vijtrip2 — APPROVED** [review]

**Comment by RedbackThomson** [comment]
/hold

Waiting for the adoption test abstract base class to be merged - https://github.com/aws-controllers-k8s/test-infra/pull/64

**Review by jaypipes — COMMENTED** [review]
@RedbackThomson the e2e test added here is for the adopted resource code paths, right? I was thinking you'd be adding an e2e test that verified the user wasn't able to set both a canned and specific ACLs at the same time? Or am I missing the context of this PR somehow?

**Comment by RedbackThomson** [comment]
> @RedbackThomson the e2e test added here is for the adopted resource code paths, right? I was thinking you'd be adding an e2e test that verified the user wasn't able to set both a canned and specific ACLs at the same time? Or am I missing the context of this PR somehow?

This PR was meant to address adopting a standard bucket, whereby it was setting both the canned ACLs and grant headers into the Spec. If a user sets both, it will ignore the grant headers and only set the canned ACL. That was already the behaviour for creating the spec manually, whereas this PR ensures that's what happens when you adopt the bucket as well.

**Comment by jaypipes** [comment]
Ah, gotcha, thanks for the explanation @RedbackThomson.

/lgtm

**Pull request merged**
