### PR TITLE
Add description for id and status field of the lifecycle spec

### PR DESCRIPTION
**Pull request by AljoschaP**
Issue #, if available: Not available

Description of changes:
In order to clarify the use of the id and status field of the lifecycle spec, this PR adds description fields to both.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — COMMENTED** [review]
Hi @AljoschaP!

Unfortunately, all of these YAML files are actually auto-generated by `controller-gen` after it looks at the Go type definitions in the `apis/v1alpha1` directory.

So, the next time the S3 controller is regenerated (which happens very often as new runtimes and aws-sdk-go's are released), the changes introduced in this PR would be overwritten.

If a field in a resource has an associated Documentation string in the API's documentation file (here is the S3 one: https://github.com/aws/aws-sdk-go/blob/main/models/apis/s3/2006-03-01/docs-2.json) then our code generation tooling *should* pick up that Documentation string. I will have to look into why these particular fields aren't getting any documentation inserted.

**Comment by AljoschaP** [comment]
Hi @jaypipes :-) Thank you for the clarification! That makes a lot of sense :+1: Sorry for the noise :man_facepalming: Should I close the PR and create an issue instead?

**Comment by jaypipes** [comment]
> Hi @jaypipes :-) Thank you for the clarification! That makes a lot of sense +1 Sorry for the noise man_facepalming Should I close the PR and create an issue instead?

Hi @AljoschaP sorry for the late response! Yes, please do create a GH issue that explains the issue. Thank you! :)

**Comment by AljoschaP** [comment]
Corresponding issue: https://github.com/aws-controllers-k8s/community/issues/1540

**Pull request closed without merging**
