### PR TITLE
Add policy for s3 replication

### PR DESCRIPTION
**Pull request by Julian-Chu**
for s3 replication, we need additional policy to assume role.

ref: https://docs.aws.amazon.com/AmazonS3/latest/userguide/setting-repl-config-perm-overview.html#receiving-replicated-objects

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
I'm cool with this as-is. I think long-term, I'd prefer to create a `config/iam/recommended-inline-policy` file that contains this content PLUS the list of specific S3-related permissions instead of the S3FullAccess AWS managed policy that currently sits in the `config/iam/recommended-policy` file.

**Comment by Julian-Chu** [comment]
> I'm cool with this as-is. I think long-term, I'd prefer to create a `config/iam/recommended-inline-policy` file that contains this content PLUS the list of specific S3-related permissions instead of the S3FullAccess AWS managed policy that currently sits in the `config/iam/recommended-policy` file.

we are using S3FullAccess as well now,  didn't review the necessary permissions,  but I can refactor the PR like the following example into `recommended-inline-policy`  in yaml or json format. WDYT?

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*",
                "s3-object-lambda:*"
            ],
            "Resource": "*"
        },
                {
            "Condition": {
                "StringEquals": {
                    "iam:PassedToService": "s3.amazonaws.com"
                }
            },
            "Action": "iam:PassRole",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```

**Comment by RedbackThomson** [comment]
> we are using S3FullAccess now, didn't review the necessary permissions before, but I can refactor the PR like the following example into `recommended-inline-policy` in yaml or json format. WDYT?

Yes please. As it stands this JSON doesn't contribute anything by itself. Moving to an inline policy keeps in line with our documented installation methods

**Review by jaypipes — APPROVED** [review]
wonderful, thank you @Julian-Chu! :)

**Review by a-hilaly — APPROVED** [review]
Thank you @Julian-Chu !
/lgtm

**Pull request merged**
