### PR TITLE
Rewrite `Bucket` tests to patch for each test

### PR DESCRIPTION
**Pull request by RedbackThomson**
Description of changes:
- Update to new E2E test bootstrapping method (no bootstrap resources, so no noticeable change for tests)
- Patch each of the `Put` fields onto a single bucket, so we can test diff, update and delete properties individually

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
/hold
Waiting for https://github.com/aws-controllers-k8s/test-infra/pull/100

**Comment by RedbackThomson** [comment]
@A-Hilaly Ready to merge?

**Comment by A-Hilaly** [comment]
Yep! :)
/lgtm

**Pull request merged**
